version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net
  
  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - net

  db:
    image: postgres:15.2-alpine3.17
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_dev:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=netadmin@nida.ac.th
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - 8081:80
    networks:
      - net

networks:
  net:

volumes:
  db_dev: